package main

import "fmt"

func main() {
	fmt.Println(foo(3))
}

func foo(a int) (b int) {
	defer func() {
		b = a + 1
	}()

	return a
}

/*
 go tool compile -S main.go
os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
        0x0000 00000 (<autogenerated>:1)        TEXT    os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
        0x0000 00000 (<autogenerated>:1)        FUNCDATA        $0, gclocals·d4dc2f11db048877dbc0f60a22b4adb3(SB)
        0x0000 00000 (<autogenerated>:1)        FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (<autogenerated>:1)        MOVQ    ""..this+8(SP), AX
        0x0005 00005 (<autogenerated>:1)        MOVQ    (AX), AX
        0x0008 00008 (<autogenerated>:1)        MOVQ    AX, ""..this+8(SP)
        0x000d 00013 (<autogenerated>:1)        XORPS   X0, X0
        0x0010 00016 (<autogenerated>:1)        MOVUPS  X0, "".~r0+16(SP)
        0x0015 00021 (<autogenerated>:1)        JMP     os.(*file).close(SB)
        0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
        0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
        rel 22+4 t=8 os.(*file).close+0
"".main STEXT size=170 args=0x0 locals=0x58
        0x0000 00000 (main.go:5)        TEXT    "".main(SB), ABIInternal, $88-0
        0x0000 00000 (main.go:5)        MOVQ    (TLS), CX
        0x0009 00009 (main.go:5)        CMPQ    SP, 16(CX)
        0x000d 00013 (main.go:5)        PCDATA  $0, $-2
        0x000d 00013 (main.go:5)        JLS     160
        0x0013 00019 (main.go:5)        PCDATA  $0, $-1
        0x0013 00019 (main.go:5)        SUBQ    $88, SP
        0x0017 00023 (main.go:5)        MOVQ    BP, 80(SP)
        0x001c 00028 (main.go:5)        LEAQ    80(SP), BP
        0x0021 00033 (main.go:5)        FUNCDATA        $0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0021 00033 (main.go:5)        FUNCDATA        $1, gclocals·f207267fbf96a0178e8758c6e3e0ce28(SB)
        0x0021 00033 (main.go:5)        FUNCDATA        $3, "".main.stkobj(SB)
        0x0021 00033 (main.go:6)        MOVQ    $3, (SP)
        0x0029 00041 (main.go:6)        PCDATA  $1, $0
        0x0029 00041 (main.go:6)        CALL    "".foo(SB)
        0x002e 00046 (main.go:6)        MOVQ    8(SP), AX
        0x0033 00051 (main.go:6)        MOVQ    AX, (SP)
        0x0037 00055 (main.go:6)        CALL    runtime.convT64(SB)
        0x003c 00060 (main.go:6)        MOVQ    8(SP), AX
        0x0041 00065 (main.go:6)        XORPS   X0, X0
        0x0044 00068 (main.go:6)        MOVUPS  X0, ""..autotmp_12+64(SP)
        0x0049 00073 (main.go:6)        LEAQ    type.int(SB), CX
        0x0050 00080 (main.go:6)        MOVQ    CX, ""..autotmp_12+64(SP)
        0x0055 00085 (main.go:6)        MOVQ    AX, ""..autotmp_12+72(SP)
        0x005a 00090 (<unknown line number>)    NOP
        0x005a 00090 ($GOROOT/src/fmt/print.go:274)     MOVQ    os.Stdout(SB), AX
        0x0061 00097 ($GOROOT/src/fmt/print.go:274)     LEAQ    go.itab.*os.File,io.Writer(SB), CX
        0x0068 00104 ($GOROOT/src/fmt/print.go:274)     MOVQ    CX, (SP)
        0x006c 00108 ($GOROOT/src/fmt/print.go:274)     MOVQ    AX, 8(SP)
        0x0071 00113 ($GOROOT/src/fmt/print.go:274)     LEAQ    ""..autotmp_12+64(SP), AX
        0x0076 00118 ($GOROOT/src/fmt/print.go:274)     MOVQ    AX, 16(SP)
        0x007b 00123 ($GOROOT/src/fmt/print.go:274)     MOVQ    $1, 24(SP)
        0x0084 00132 ($GOROOT/src/fmt/print.go:274)     MOVQ    $1, 32(SP)
        0x008d 00141 ($GOROOT/src/fmt/print.go:274)     CALL    fmt.Fprintln(SB)
        0x0092 00146 (main.go:6)        MOVQ    80(SP), BP
        0x0097 00151 (main.go:6)        ADDQ    $88, SP
        0x009b 00155 (main.go:6)        RET
        0x009c 00156 (main.go:6)        NOP
        0x009c 00156 (main.go:5)        PCDATA  $1, $-1
        0x009c 00156 (main.go:5)        PCDATA  $0, $-2
        0x009c 00156 (main.go:5)        NOP
        0x00a0 00160 (main.go:5)        CALL    runtime.morestack_noctxt(SB)
        0x00a5 00165 (main.go:5)        PCDATA  $0, $-1
        0x00a5 00165 (main.go:5)        JMP     0
        0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 8d  dH..%....H;a....
        0x0010 00 00 00 48 83 ec 58 48 89 6c 24 50 48 8d 6c 24  ...H..XH.l$PH.l$
        0x0020 50 48 c7 04 24 03 00 00 00 e8 00 00 00 00 48 8b  PH..$.........H.
        0x0030 44 24 08 48 89 04 24 e8 00 00 00 00 48 8b 44 24  D$.H..$.....H.D$
        0x0040 08 0f 57 c0 0f 11 44 24 40 48 8d 0d 00 00 00 00  ..W...D$@H......
        0x0050 48 89 4c 24 40 48 89 44 24 48 48 8b 05 00 00 00  H.L$@H.D$HH.....
        0x0060 00 48 8d 0d 00 00 00 00 48 89 0c 24 48 89 44 24  .H......H..$H.D$
        0x0070 08 48 8d 44 24 40 48 89 44 24 10 48 c7 44 24 18  .H.D$@H.D$.H.D$.
        0x0080 01 00 00 00 48 c7 44 24 20 01 00 00 00 e8 00 00  ....H.D$ .......
        0x0090 00 00 48 8b 6c 24 50 48 83 c4 58 c3 0f 1f 40 00  ..H.l$PH..X...@.
        0x00a0 e8 00 00 00 00 e9 56 ff ff ff                    ......V...
        rel 5+4 t=17 TLS+0
        rel 42+4 t=8 "".foo+0
        rel 56+4 t=8 runtime.convT64+0
        rel 76+4 t=16 type.int+0
        rel 93+4 t=16 os.Stdout+0
        rel 100+4 t=16 go.itab.*os.File,io.Writer+0
        rel 142+4 t=8 fmt.Fprintln+0
        rel 161+4 t=8 runtime.morestack_noctxt+0
"".foo STEXT size=165 args=0x10 locals=0x38
        0x0000 00000 (main.go:9)        TEXT    "".foo(SB), ABIInternal, $56-16
        0x0000 00000 (main.go:9)        MOVQ    (TLS), CX
        0x0009 00009 (main.go:9)        CMPQ    SP, 16(CX)
        0x000d 00013 (main.go:9)        PCDATA  $0, $-2
        0x000d 00013 (main.go:9)        JLS     151
        0x0013 00019 (main.go:9)        PCDATA  $0, $-1
        0x0013 00019 (main.go:9)        SUBQ    $56, SP
        0x0017 00023 (main.go:9)        MOVQ    BP, 48(SP)
        0x001c 00028 (main.go:9)        LEAQ    48(SP), BP
        0x0021 00033 (main.go:9)        XORPS   X0, X0
        0x0024 00036 (main.go:9)        MOVUPS  X0, 32(SP)
        0x0029 00041 (main.go:9)        FUNCDATA        $0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
        0x0029 00041 (main.go:9)        FUNCDATA        $1, gclocals·e226d4ae4a7cad8835311c6a4683c14f(SB)
        0x0029 00041 (main.go:9)        FUNCDATA        $5, "".foo.opendefer(SB)
        0x0029 00041 (main.go:9)        MOVB    $0, ""..autotmp_3+23(SP)
        0x002e 00046 (main.go:9)        MOVQ    $0, "".b+72(SP)
        0x0037 00055 (main.go:10)       LEAQ    "".foo.func1·f(SB), AX
        0x003e 00062 (main.go:10)       MOVQ    AX, ""..autotmp_4+40(SP)
        0x0043 00067 (main.go:10)       MOVQ    "".a+64(SP), AX
        0x0048 00072 (main.go:10)       MOVQ    AX, ""..autotmp_5+24(SP)
        0x004d 00077 (main.go:10)       LEAQ    "".b+72(SP), CX
        0x0052 00082 (main.go:10)       MOVQ    CX, ""..autotmp_6+32(SP)
        0x0057 00087 (main.go:10)       MOVB    $1, ""..autotmp_3+23(SP)
        0x005c 00092 (main.go:14)       MOVQ    AX, "".b+72(SP)
        0x0061 00097 (main.go:14)       MOVB    $0, ""..autotmp_3+23(SP)
        0x0066 00102 (main.go:14)       MOVQ    ""..autotmp_5+24(SP), AX
        0x006b 00107 (main.go:14)       MOVQ    AX, (SP)
        0x006f 00111 (main.go:14)       MOVQ    ""..autotmp_6+32(SP), AX
        0x0074 00116 (main.go:14)       MOVQ    AX, 8(SP)
        0x0079 00121 (main.go:14)       PCDATA  $1, $1
        0x0079 00121 (main.go:14)       CALL    "".foo.func1(SB)
        0x007e 00126 (main.go:14)       MOVQ    48(SP), BP
        0x0083 00131 (main.go:14)       ADDQ    $56, SP
        0x0087 00135 (main.go:14)       RET
        0x0088 00136 (main.go:14)       CALL    runtime.deferreturn(SB)
        0x008d 00141 (main.go:14)       MOVQ    48(SP), BP
        0x0092 00146 (main.go:14)       ADDQ    $56, SP
        0x0096 00150 (main.go:14)       RET
        0x0097 00151 (main.go:14)       NOP
        0x0097 00151 (main.go:9)        PCDATA  $1, $-1
        0x0097 00151 (main.go:9)        PCDATA  $0, $-2
        0x0097 00151 (main.go:9)        CALL    runtime.morestack_noctxt(SB)
        0x009c 00156 (main.go:9)        PCDATA  $0, $-1
        0x009c 00156 (main.go:9)        NOP
        0x00a0 00160 (main.go:9)        JMP     0
        0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 84  dH..%....H;a....
        0x0010 00 00 00 48 83 ec 38 48 89 6c 24 30 48 8d 6c 24  ...H..8H.l$0H.l$
        0x0020 30 0f 57 c0 0f 11 44 24 20 c6 44 24 17 00 48 c7  0.W...D$ .D$..H.
        0x0030 44 24 48 00 00 00 00 48 8d 05 00 00 00 00 48 89  D$H....H......H.
        0x0040 44 24 28 48 8b 44 24 40 48 89 44 24 18 48 8d 4c  D$(H.D$@H.D$.H.L
        0x0050 24 48 48 89 4c 24 20 c6 44 24 17 01 48 89 44 24  $HH.L$ .D$..H.D$
        0x0060 48 c6 44 24 17 00 48 8b 44 24 18 48 89 04 24 48  H.D$..H.D$.H..$H
        0x0070 8b 44 24 20 48 89 44 24 08 e8 00 00 00 00 48 8b  .D$ H.D$......H.
        0x0080 6c 24 30 48 83 c4 38 c3 e8 00 00 00 00 48 8b 6c  l$0H..8......H.l
        0x0090 24 30 48 83 c4 38 c3 e8 00 00 00 00 0f 1f 40 00  $0H..8........@.
        0x00a0 e9 5b ff ff ff                                   .[...
        rel 5+4 t=17 TLS+0
        rel 58+4 t=16 "".foo.func1·f+0
        rel 122+4 t=8 "".foo.func1+0
        rel 137+4 t=8 runtime.deferreturn+0
        rel 152+4 t=8 runtime.morestack_noctxt+0
"".foo.func1 STEXT nosplit size=17 args=0x10 locals=0x0
        0x0000 00000 (main.go:10)       TEXT    "".foo.func1(SB), NOSPLIT|ABIInternal, $0-16
        0x0000 00000 (main.go:10)       FUNCDATA        $0, gclocals·889056d0e48497e303e8c1b58a2a5458(SB)
        0x0000 00000 (main.go:10)       FUNCDATA        $1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
        0x0000 00000 (main.go:11)       MOVQ    "".a+8(SP), AX
        0x0005 00005 (main.go:11)       INCQ    AX
        0x0008 00008 (main.go:11)       MOVQ    "".&b+16(SP), CX
        0x000d 00013 (main.go:11)       MOVQ    AX, (CX)
        0x0010 00016 (main.go:12)       RET
        0x0000 48 8b 44 24 08 48 ff c0 48 8b 4c 24 10 48 89 01  H.D$.H..H.L$.H..
        0x0010 c3                                               .
go.cuinfo.packagename. SDWARFINFO dupok size=0
        0x0000 6d 61 69 6e                                      main
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
        0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
        0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
        0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
        rel 0+0 t=24 type.[]interface {}+0
        rel 0+0 t=24 type.error+0
        rel 0+0 t=24 type.int+0
        rel 19+4 t=29 go.info.[]interface {}+0
        rel 27+4 t=29 go.info.int+0
        rel 37+4 t=29 go.info.error+0
runtime.nilinterequal·f SRODATA dupok size=8
        0x0000 00 00 00 00 00 00 00 00                          ........
        rel 0+8 t=1 runtime.nilinterequal+0
runtime.memequal64·f SRODATA dupok size=8
        0x0000 00 00 00 00 00 00 00 00                          ........
        rel 0+8 t=1 runtime.memequal64+0
runtime.gcbits.01 SRODATA dupok size=1
        0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
        0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
        0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
        0x0010 4f 0f 96 9d 08 08 08 36 00 00 00 00 00 00 00 00  O......6........
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00                          ........
        rel 24+8 t=1 runtime.memequal64·f+0
        rel 32+8 t=1 runtime.gcbits.01+0
        rel 40+4 t=5 type..namedata.*interface {}-+0
        rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
        0x0000 02                                               .
type.interface {} SRODATA dupok size=80
        0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
        0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        rel 24+8 t=1 runtime.nilinterequal·f+0
        rel 32+8 t=1 runtime.gcbits.02+0
        rel 40+4 t=5 type..namedata.*interface {}-+0
        rel 44+4 t=6 type.*interface {}+0
        rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
        0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface
        0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
        0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
        0x0010 f3 04 9a e7 08 08 08 36 00 00 00 00 00 00 00 00  .......6........
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00                          ........
        rel 24+8 t=1 runtime.memequal64·f+0
        rel 32+8 t=1 runtime.gcbits.01+0
        rel 40+4 t=5 type..namedata.*[]interface {}-+0
        rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
        0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
        0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00                          ........
        rel 32+8 t=1 runtime.gcbits.01+0
        rel 40+4 t=5 type..namedata.*[]interface {}-+0
        rel 44+4 t=6 type.*[]interface {}+0
        rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
        0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
        0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
        0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
        0x0010 bf 03 a8 35 08 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00                          ........
        rel 24+8 t=1 runtime.memequal64·f+0
        rel 32+8 t=1 runtime.gcbits.01+0
        rel 40+4 t=5 type..namedata.*[1]interface {}-+0
        rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
        0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
        0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
        0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0040 01 00 00 00 00 00 00 00                          ........
        rel 24+8 t=1 runtime.nilinterequal·f+0
        rel 32+8 t=1 runtime.gcbits.02+0
        rel 40+4 t=5 type..namedata.*[1]interface {}-+0
        rel 44+4 t=6 type.*[1]interface {}+0
        rel 48+8 t=1 type.interface {}+0
        rel 56+8 t=1 type.[]interface {}+0
""..inittask SNOPTRDATA size=32
        0x0000 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00  ................
        0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        rel 24+8 t=1 fmt..inittask+0
"".foo.func1·f SRODATA dupok size=8
        0x0000 00 00 00 00 00 00 00 00                          ........
        rel 0+8 t=1 "".foo.func1+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
        0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
        0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
        rel 0+8 t=1 type.io.Writer+0
        rel 8+8 t=1 type.*os.File+0
        rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
        0x0000 00 00 00 00 00 00 00 00                          ........
        rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.fmt. SRODATA dupok size=6
        0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·d4dc2f11db048877dbc0f60a22b4adb3 SRODATA dupok size=9
        0x0000 01 00 00 00 03 00 00 00 01                       .........
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
        0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·f207267fbf96a0178e8758c6e3e0ce28 SRODATA dupok size=9
        0x0000 01 00 00 00 02 00 00 00 00                       .........
"".main.stkobj SRODATA size=24
        0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
        0x0010 00 00 00 00 00 00 00 00                          ........
        rel 16+8 t=1 type.[1]interface {}+0
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
        0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·e226d4ae4a7cad8835311c6a4683c14f SRODATA dupok size=10
        0x0000 02 00 00 00 02 00 00 00 00 03                    ..........
"".foo.opendefer SRODATA dupok size=12
        0x0000 10 19 01 10 08 02 18 08 00 10 08 08              ............
gclocals·889056d0e48497e303e8c1b58a2a5458 SRODATA dupok size=9
        0x0000 01 00 00 00 02 00 00 00 02                       .........

*/
